name: 'ascendion'
version: '1.0.0'
profile: 'ascendion'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ascendion:
    staging:
      +materialized: view
    marts:
      +materialized: table